### ISSUE TITLE
Truck Add/Edit - Traffic Lights - Signal on tare

### ISSUE THREAD

**Issue by sspoon865** [TAC-Insight/fw-scale-frontend#239]
Rework truck tare combobox/selector to pull from Lane configs for scales instead of serial ports so that it is possible to signal the assigned traffic lights (if any) of a lane.

**Comment by HaleyBoles** [comment]
@sspoon865 This was originally set up to use serial ports for scales to show all configured scales on truck screen, instead of only those assigned to lanes. 

I think you could get around this by getting scales from lanes, then also appending any other scales set up that are not assigned to a lane. Probably edge case, but I could see adding in a tare-only scale that isn't set up on a lane that you would need in truck edit/tare screen.

**Comment by HaleyBoles** [comment]
https://github.com/TAC-Insight/fw-scale-frontend/issues/296
