### ISSUE TITLE
User Authorization

### ISSUE THREAD

**Issue by ericwilhite** [TAC-Insight/fw-scale-frontend#98]
🔐 Check user permissions for screen / action access

**Comment by HaleyBoles** [comment]
@ericwilhite @sspoon865 I have this branch to a point where it is working and I implemented the <Show> component. Pls feel free to take a look and see how we feel before we proceed. 

Most places <Show> is used, we could wrap the "when" into the component (IE the AppLayout NavLink or Buttons) instead or obviously just do inline conditional show/hide. Any choice is just about readability and reusability for us and won't change how it looks on the front end.

I am leaning more to just putting "when" into components after building some of it out and using that for most things instead of inline conditionals or <Show>. This option however doesn't work out of the box for standard HTML tags like DIVs.
